server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ai-service-route
          uri: lb://ai-service
          predicates:
            - Path=/ai/**
          filters:
            - StripPrefix=1
        - id: empire-manager-erp-route
          uri: lb://empire-manager-erp
          predicates:
            - Path=/empire/**
          filters:
            - StripPrefix=1


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
