server:
  port: 8083

spring:
  application:
    name: project-analysis
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/supersys-relational-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  graphql:
    graphiql:
      enabled: true
      path: /graphiql


services:
  ai-service:
    url: ${AI_SERVICE_URL:http://ai-service:8082}
  lambda-service:
    url: ${LAMBDA_SERVICE_URL:http://lambda-service:8080}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
