spring:
  application:
    name: ai-service
  config:
    import: "optional:configserver:http://localhost:8888"
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
  ai:
    mcp:
      client:
        stdio:
          servers:
            github-server:
              command: npx
              args:
                - "-y"
                - "@modelcontextprotocol/server-github"
              env:
                GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_TOKEN}