server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: coordinator-route
          uri: lb://coordinator-service
          predicates:
            - Path=/coordinator/**
          filters:
            - StripPrefix=1
        - id: function-route
          uri: lb://function-service
          predicates:
            - Path=/function/**
          filters:
            - StripPrefix=1
        - id: ai-service-route
          uri: lb://ai-service
          predicates:
            - Path=/ai/**
          filters:
            - StripPrefix=1
        - id: empire-manager-erp-route
          uri: lb://empire-manager-erp
          predicates:
            - Path=/empire/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
