server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/supersys_vector_db
    username: apm
    password: super_password_2026
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY:placeholder_api_key}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-v4-flash
    vectorstore:
      pgvector:
        table-name: vector_store
        dimension: 384
        initialize-schema: true
