server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ai-service-route
          uri: lb://ai-service
          predicates:
            - Path=/ai/**
          filters:
            - StripPrefix=1
        - id: lambda-service-route
          uri: lb://lambda-service
          predicates:
            - Path=/lambda/**
          filters:
            - StripPrefix=1
        - id: project-analysis-route
          uri: lb://project-analysis
          predicates:
            - Path=/project-analysis/**
          filters:
            - StripPrefix=1



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
