spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPO_URI}
          username: ${GIT_USERNAME:${GIT_TOKEN:}}
          password: ${GIT_PASSWORD:${GIT_TOKEN:}}
          search-paths: ${GIT_SEARCH_PATHS:}
          clone-on-start: true
          default-label: ${GIT_DEFAULT_LABEL:main}
          force-pull: true

